Ubuntu

diff --git a/.github/actions/macos-build-system/action.yml b/.github/actions/macos-build-system/action.yml
--- a/.github/actions/macos-build-system/action.yml
+++ b/.github/actions/macos-build-system/action.yml
@@ -12,18 +12,18 @@ inputs:
 runs:
   using: 'composite'
   steps:
-    - name: Init environment
-      run: |
-        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
-        echo "SCCACHE_C_CUSTOM_CACHE_BUSTER=${{ inputs.job-id }}" >> $GITHUB_ENV
-        echo "SCCACHE_CONF=${GITHUB_WORKSPACE}/sccache_config" >> $GITHUB_ENV
-        echo "SCCACHE_ERROR_LOG=${{ github.workspace }}/sccache.log" >> $GITHUB_ENV
-        # LogLevel in {error, warn, info, debug, trace}, see parse.rs
-        echo "SCCACHE_LOG=debug" >> $GITHUB_ENV
-        echo "CMAKE_CXX_COMPILER_LAUNCHER=sccache" >> $GITHUB_ENV
-        echo "CMAKE_C_COMPILER_LAUNCHER=sccache" >> $GITHUB_ENV
-        echo "BOOST_INSTALL_LAYOUT=system" >> $GITHUB_ENV
-      shell: bash
+    #- name: Init environment
+      #run: |
+        #echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
+        #echo "SCCACHE_C_CUSTOM_CACHE_BUSTER=${{ inputs.job-id }}" >> $GITHUB_ENV
+        #echo "SCCACHE_CONF=${GITHUB_WORKSPACE}/sccache_config" >> $GITHUB_ENV
+        #echo "SCCACHE_ERROR_LOG=${{ github.workspace }}/sccache.log" >> $GITHUB_ENV
+        ## LogLevel in {error, warn, info, debug, trace}, see parse.rs
+        #echo "SCCACHE_LOG=debug" >> $GITHUB_ENV
+        #echo "CMAKE_CXX_COMPILER_LAUNCHER=sccache" >> $GITHUB_ENV
+        #echo "CMAKE_C_COMPILER_LAUNCHER=sccache" >> $GITHUB_ENV
+        #echo "BOOST_INSTALL_LAYOUT=system" >> $GITHUB_ENV
+      #shell: bash
     # Debug
     #- uses: mxschmitt/action-tmate@v3
 
@@ -43,20 +43,20 @@ runs:
       uses: mozilla-actions/sccache-action@v0.0.5
 
 
-    # Initialize Conan with local packages
-    - name: Initialize Conan
-      working-directory: ${{ github.workspace }}/LuxCore
-      env:
-        PKG_CONFIG_PATH: .
-      run: |
-        set -o pipefail
+    ## Initialize Conan with local packages
+    #- name: Initialize Conan
+      #working-directory: ${{ github.workspace }}/LuxCore
+      #env:
+        #PKG_CONFIG_PATH: .
+      #run: |
+        #set -o pipefail
 
-        # Copy profiles
-        _profile="${{ github.workspace }}/conan_profile_${RUNNER_OS}_${RUNNER_ARCH}"
-        echo "Copying profile ${_profile}"
-        mkdir -p ~/.conan2/profiles
-        cp ${_profile} ~/.conan2/profiles/default
+        ## Copy profiles
+        #_profile="${{ github.workspace }}/conan_profile_${RUNNER_OS}_${RUNNER_ARCH}"
+        #echo "Copying profile ${_profile}"
+        #mkdir -p ~/.conan2/profiles
+        #cp ${_profile} ~/.conan2/profiles/default
 
-        cp ../conanfile.py .
-        unset ORIGINAL_PATH
-      shell: bash
+        #cp ../conanfile.py .
+        #unset ORIGINAL_PATH
+      #shell: bash
